Cps 596 testlink integration
compucorp/cases-product-suite-e2e-tests pull request #2
Opened 2021-06-07 07:05 UTC by deb1990

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2021-06-16 20:00 UTC, reneolivo requested changes

2021-06-16 20:00 UTC, reneolivo commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +    }
consider using the strategy pattern to avoid infinite conditions:

```ts
const isRootDescribeBlock = event.describeBlock.parent?.name === 'ROOT_DESCRIBE_BLOCK';
const eventHandlers = {
  setup: { run: () => this.beforeAllTests() },
  run_describe_start: { run: () => this.beforeAllTestsOfEachSpecFile(), canRun: () => isRootDescribeBlock },
  // ...
};

const eventHandler = eventHandlers[event.name];

if (eventHandler &&  ((eventhandler.canRun && eventHandler.canRun()) || true) {
  await eventHandler.run();
}
```

2021-06-16 20:00 UTC, reneolivo commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +    return name.substr(0, name.indexOf('::'));
it would be good to include an example of the original name and the expected output in the description of this function.

2021-06-16 20:00 UTC, reneolivo commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +  getTestName (test: Circus.TestEntry | Circus.DescribeBlock, name: Circus.TestName[]): Circus.TestName[] {
Is the linter forcing to declare the return type of the function? Return types are inferred by typescript. I believe it's distracting and more verbose to manually declare the type.

2021-06-16 20:00 UTC, reneolivo commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +  }
`getTestLinkID` and `getTestName` seem helper functions not related to the purpose of this class. Consider moving them to a separate class or function.

2021-06-16 20:00 UTC, reneolivo commented on tests/awards/manage-applications/awards-page-title.spec.ts
> +declare const global: JestGlobal;
you don't have to declare the jest global every time, you can create a `.d.ts` file:
https://stackoverflow.com/questions/21247278/about-d-ts-in-typescript

2021-06-17 06:48 UTC, deb1990 commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +  getTestName (test: Circus.TestEntry | Circus.DescribeBlock, name: Circus.TestName[]): Circus.TestName[] {
Yes it forced by the linter, lets have a quick call about this.

2021-06-17 08:08 UTC, deb1990 commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +  }
Moved `getTestLinkID `. But not sure about `getTestName`, lets discuss.

2021-06-17 08:15 UTC, deb1990 commented on tests/awards/manage-applications/awards-page-title.spec.ts
> +declare const global: JestGlobal;
Here the case is a bit different. As the variable `global` itself is needed. Lets discuss.

2021-06-17 16:30 UTC, deb1990 commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +    }
I was not able to fix this for now, we have discussed some solutions, but they are also not perfect. So I would say, lets keep it like this, and I will try to figure this out as soon as possible.

2021-06-17 16:35 UTC, deb1990 commented on gulp-tasks/jest-helper/environments/e2e-test-environment.ts
> +  getTestName (test: Circus.TestEntry | Circus.DescribeBlock, name: Circus.TestName[]): Circus.TestName[] {
Also as discussed, this one is depends on the opinion of the dev, and as Standard JS is enforcing this, lets keep it like this for now.

2021-06-17 16:58 UTC, deb1990 commented on tests/awards/manage-applications/awards-page-title.spec.ts
> +declare const global: JestGlobal;
I tried as per our discussion, but still could not figure this out. Lets keep it as it is, and we can change this later.

2021-06-18 11:56 UTC, reneolivo approved these changes

2021-06-18 11:56 UTC, merged